@startuml
skinparam classAttributeIconSize 0
skinparam groupInheritance 2

'7 Sequence Diagram
'Homework 1-1
'Sequence Diagram

title 
Hoemwork 1-1
Customer Item Order 
Sequence Diagram

end title

participant Customer
participant Item

Customer -> Item : Order
Customer <-- Item : Deliver

@enduml