@startuml
title Sequence Diagram Test

participant Alice [
    alice: Orange World
]

participant Bob [
    : Bob
]

Alice -> Bob : Hi
Bob --> Alice : ACK

Alice -> Bob : Auth Req

'alt is switch
alt successful case
'note center alt is switch end note
    Bob -> Alice : Auth Accepted
end

@enduml